In [1]:
import pandas as pd
import numpy as np
from IPython.display import display

In [2]:
# try appearance and games merging for future improvements

In [3]:
df1 = pd.read_excel('players.xlsx')
df1.head()

,player_id,name,last_season,current_club_id,player_code,country_of_birth,date_of_birth,sub_position,position,foot,height_in_cm,market_value_in_eur,highest_market_value_in_eur,contract_expiration_date,agent_name
0,124732,John Anthony Brooks,2023,533,john-anthony-brooks,Germany,1993-01-28,Centre-Back,Defender,left,194.0,2000000.0,15000000.0,2024-06-30,ROGON
1,223047,Emerson Hyndman,2018,903,emerson-hyndman,United States,1996-04-09,Central Midfield,Midfield,right,170.0,800000.0,1800000.0,NaT,OmniSports
2,307781,Lynden Gooch,2016,289,lynden-gooch,United States,1995-12-24,Right Winger,Attack,right,173.0,1000000.0,1000000.0,2024-06-30,Unique Sports Group
3,370846,Timothy Weah,2023,506,timothy-weah,United States,2000-02-22,Right Midfield,Midfield,right,183.0,14000000.0,15000000.0,2028-06-30,BS Group - BS Law
4,484756,Djordje Mihailovic,2023,1090,djordje-mihailovic,United States,1998-11-10,Attacking Midfield,Midfield,NaN,178.0,5000000.0,6000000.0,2026-06-30,YMU Management Ltd.

In [4]:
df2 = pd.read_excel('games.xlsx')
df2.head()

,game_id,competition_id,season,round,date,home_club_goals,away_club_goals,home_club_position,away_club_position,home_club_manager_name,away_club_manager_name,stadium,attendance,referee,home_club_formation,away_club_formation,home_club_name,away_club_name,aggregate,competition_type
0,2222734,RU1,2012,19. Matchday,2012-12-07,2,3,11.0,10.0,Miodrag Bozovic,Slavoljub Muslin,Olimp-2,5700.0,Sergey Kuznetsov,NaN,NaN,FK Rostov,FK Krasnodar,02:03:00,domestic_league
1,2224572,DK1,2012,3. Matchday,2012-07-28,1,2,12.0,1.0,Jess Thorup,Lars Sondergaard,Blue Water Arena,5345.0,Michael Svendsen,NaN,NaN,Esbjerg fB,Sonderjyske Fc,01:02:00,domestic_league
2,2224628,DK1,2012,22. Matchday,2013-03-08,2,0,3.0,10.0,Colin Todd,Lars Sondergaard,Cepheus Park Randers,3481.0,Jakob Kehlet,NaN,NaN,Randers Fodbold Club,Sonderjyske Fc,02:00:00,domestic_league
3,2224655,DK1,2012,22. Matchday,2013-03-10,0,3,6.0,12.0,Peter Rensen,Auri Skarbalius,Ceres Park,7967.0,Kenn Hansen,NaN,NaN,Aarhus Gymnastik Forening,BRA NDBYERNES,00:03:00,domestic_league
4,2224729,DK1,2012,1. Matchday,2012-07-15,0,1,9.0,5.0,Auri Skarbalius,Troels Bech,Brondby Stadium,10806.0,Lars Christoffersen,NaN,NaN,Brondby IF,Odense Boldklub,00:01:00,domestic_league

In [5]:
df3 = pd.read_excel('game_lineups.xlsx')
df3.head()

,game_lineups_id,game_id,type,number,player_id,player_name,team_captain,position
0,f2570d1504fc02f4b6c7608e8dcf89a3,4087925,substitutes,34,242284,Ethan Horvath,0,Goalkeeper
1,f5f0da93ea8e1d8bdd799658e7c8f7cb,4087928,starting_lineup,13,145466,Tim Ream,0,Centre-Back
2,31a4d12ec23d604779d909d26c1b5410,4087929,substitutes,26,578539,Chris Richards,0,Centre-Back
3,776dcbef98651450db76723cb7e3b4df,4087935,substitutes,26,578539,Chris Richards,0,Centre-Back
4,6a35ef7495303f29e7f85dbd54547fb1,4087936,starting_lineup,13,145466,Tim Ream,1,Centre-Back

In [6]:
df4 = pd.read_excel('game_events.xlsx')
df4.head()

,game_event_id,date,game_id,minute,type,player_id,description,player_in_id,player_assist_id
0,c6a3c088ed8a38d4ce074dd73b20d3da,2012-08-19,2221641,62,Substitutions,1335,", Not reported",45668.0,NaN
1,02d605a5c2dc4f9a6721daa583fa5405,2012-08-26,2222536,54,Cards,1321,"1. Yellow card , Foul",NaN,NaN
2,b56c2e2e087cddb3cfe9e3d340975df9,2012-11-18,2222707,79,Substitutions,104203,", Tactical",25740.0,NaN
3,4a15d1fff4f476f48bb60092c61641d5,2012-11-23,2222721,72,Substitutions,104203,", Tactical",15583.0,NaN
4,daa97877f7edf2fda885b411d7197921,2013-05-17,2222782,63,Goals,104203,", Right-footed shot, 1. Goal of the Season Ass...",NaN,15077.0

In [7]:
df5 = pd.read_excel('appearances.xlsx')
df5.head()

,appearance_id,game_id,player_id,date,player_name,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
0,2224728_119169,2224728,119169,2012-07-13,Aron Johannsson,DK1,0,0,0,0,90
1,2224732_161244,2224732,161244,2012-07-14,Conor O'Brien,DK1,0,0,1,0,90
2,2224729_39467,2224729,39467,2012-07-15,Clarence Goodson,DK1,0,0,0,0,90
3,2232104_119169,2232104,119169,2012-07-19,Aron Johannsson,ELQ,0,0,0,0,74
4,2219794_39475,2219794,39475,2012-07-22,Sacha Kljestan,BESC,0,0,0,0,3

In [8]:
# df2,df3
df_concat_1 = df2.merge(df3, on = 'game_id', how = 'outer')
df_concat_1

,game_id,competition_id,season,round,date,home_club_goals,away_club_goals,home_club_position,away_club_position,home_club_manager_name,...,away_club_name,aggregate,competition_type,game_lineups_id,type,number,player_id,player_name,team_captain,position
0,2222734,RU1,2012.0,19. Matchday,2012-12-07,2.0,3.0,11.0,10.0,Miodrag Bozovic,...,FK Krasnodar,02:03:00,domestic_league,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2224572,DK1,2012.0,3. Matchday,2012-07-28,1.0,2.0,12.0,1.0,Jess Thorup,...,Sonderjyske Fc,01:02:00,domestic_league,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2224628,DK1,2012.0,22. Matchday,2013-03-08,2.0,0.0,3.0,10.0,Colin Todd,...,Sonderjyske Fc,02:00:00,domestic_league,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2224655,DK1,2012.0,22. Matchday,2013-03-10,0.0,3.0,6.0,12.0,Peter Rensen,...,BRA NDBYERNES,00:03:00,domestic_league,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2224729,DK1,2012.0,1. Matchday,2012-07-15,0.0,1.0,9.0,5.0,Auri Skarbalius,...,Odense Boldklub,00:01:00,domestic_league,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3482,4194152,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,ec3d266094f99ca0a8847de827e37105,starting_lineup,7.0,504215.0,Giovanni Reyna,0.0,Right Winger
3483,4194152,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,667840cda9bdf3b0344b8e99b306cf38,starting_lineup,23.0,124732.0,John Anthony Brooks,0.0,Centre-Back
3484,4194154,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1c5d2f60ee777760f8a757aa10c42bb1,starting_lineup,13.0,103064.0,Terrence Boyd,0.0,Centre-Forward
3485,4204000,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,99032084fd00ffbfee52c541a9f960ab,substitutes,14.0,315762.0,Luca de la Torre,0.0,Central Midfield
3486,4220942,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,5c9eaf6ebb621d43a0d6fd6a9e607ef9,substitutes,13.0,145466.0,Tim Ream,0.0,Centre-Back

In [9]:
# df5,df1
df_concat_2 = df1.merge(df5, on = 'player_id', how = 'outer') 

df_concat_2

,player_id,name,last_season,current_club_id,player_code,country_of_birth,date_of_birth,sub_position,position,foot,...,appearance_id,game_id,date,player_name,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
0,124732,John Anthony Brooks,2023,533,john-anthony-brooks,Germany,1993-01-28,Centre-Back,Defender,left,...,2320457_124732,2320457.0,2013-08-04,John Anthony Brooks,DFB,0.0,0.0,0.0,0.0,120.0
1,124732,John Anthony Brooks,2023,533,john-anthony-brooks,Germany,1993-01-28,Centre-Back,Defender,left,...,2321034_124732,2321034.0,2013-08-10,John Anthony Brooks,L1,0.0,0.0,1.0,0.0,90.0
2,124732,John Anthony Brooks,2023,533,john-anthony-brooks,Germany,1993-01-28,Centre-Back,Defender,left,...,2321049_124732,2321049.0,2013-08-18,John Anthony Brooks,L1,0.0,0.0,0.0,0.0,8.0
3,124732,John Anthony Brooks,2023,533,john-anthony-brooks,Germany,1993-01-28,Centre-Back,Defender,left,...,2321061_124732,2321061.0,2013-08-24,John Anthony Brooks,L1,0.0,0.0,0.0,0.0,23.0
4,124732,John Anthony Brooks,2023,533,john-anthony-brooks,Germany,1993-01-28,Centre-Back,Defender,left,...,2321067_124732,2321067.0,2013-08-31,John Anthony Brooks,L1,0.0,0.0,0.0,0.0,90.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3623,504215,Giovanni Reyna,2023,16,giovanni-reyna,England,2002-11-13,Attacking Midfield,Midfield,right,...,3203722_504215,3203722.0,2020-06-20,Giovanni Reyna,L1,1.0,0.0,0.0,1.0,81.0
3624,504215,Giovanni Reyna,2023,16,giovanni-reyna,England,2002-11-13,Attacking Midfield,Midfield,right,...,3203730_504215,3203730.0,2020-06-27,Giovanni Reyna,L1,0.0,0.0,0.0,0.0,65.0
3625,504215,Giovanni Reyna,2023,16,giovanni-reyna,England,2002-11-13,Attacking Midfield,Midfield,right,...,3404450_504215,3404450.0,2020-09-14,Giovanni Reyna,DFB,0.0,0.0,1.0,0.0,57.0
3626,504215,Giovanni Reyna,2023,16,giovanni-reyna,England,2002-11-13,Attacking Midfield,Midfield,right,...,3412884_504215,3412884.0,2020-09-19,Giovanni Reyna,L1,0.0,0.0,1.0,1.0,79.0
3627,504215,Giovanni Reyna,2023,16,giovanni-reyna,England,2002-11-13,Attacking Midfield,Midfield,right,...,3412908_504215,3412908.0,2020-09-26,Giovanni Reyna,L1,0.0,0.0,0.0,0.0,90.0

In [10]:
df_concat_2.isnull().sum()

player_id                         0
name                              0
last_season                       0
current_club_id                   0
player_code                       0
country_of_birth                  0
date_of_birth                     0
sub_position                      0
position                          0
foot                             94
height_in_cm                     52
market_value_in_eur            1229
highest_market_value_in_eur       4
contract_expiration_date       1358
agent_name                     1036
appearance_id                    60
game_id                          60
date                             60
player_name                      60
competition_id                   60
yellow_cards                     60
red_cards                        60
goals                            60
assists                          60
minutes_played                   60
dtype: int64

In [11]:
df_concat_3 = df_concat_2.merge(df2, on = 'game_id', how = 'outer')
df_concat_3.head()

D:\Anaconda\lib\site-packages\pandas\core\reshape\merge.py:1204: RuntimeWarning: invalid value encountered in cast
  if not (lk == lk.astype(rk.dtype))[~np.isnan(lk)].all():

,player_id,name,last_season,current_club_id,player_code,country_of_birth,date_of_birth,sub_position,position,foot,...,away_club_manager_name,stadium,attendance,referee,home_club_formation,away_club_formation,home_club_name,away_club_name,aggregate,competition_type
0,124732,John Anthony Brooks,2023,533,john-anthony-brooks,Germany,1993-01-28,Centre-Back,Defender,left,...,Jos Luhukay,Grummi Arena,5446.0,Benjamin Cortus,NaN,NaN,NaN,Hertha BSC,02:03:00,domestic_cup
1,124732,John Anthony Brooks,2023,533,john-anthony-brooks,Germany,1993-01-28,Centre-Back,Defender,left,...,Armin Veh,Olympiastadion Berlin,54376.0,Michael Weiner,NaN,NaN,Hertha BSC,eintracht frankfurt Football ag,06:01:00,domestic_league
2,124732,John Anthony Brooks,2023,533,john-anthony-brooks,Germany,1993-01-28,Centre-Back,Defender,left,...,Jos Luhukay,Max-Morlock-Stadion,37068.0,Guido Winkmann,NaN,NaN,1.FC Nuremberg,Hertha BSC,02:02:00,domestic_league
3,49723,Timothy Chandler,2023,24,timothy-chandler,Germany,1990-03-29,Right-Back,Defender,right,...,Jos Luhukay,Max-Morlock-Stadion,37068.0,Guido Winkmann,NaN,NaN,1.FC Nuremberg,Hertha BSC,02:02:00,domestic_league
4,124732,John Anthony Brooks,2023,533,john-anthony-brooks,Germany,1993-01-28,Centre-Back,Defender,left,...,Thorsten Fink,Olympiastadion Berlin,63574.0,Marco Fritz,NaN,NaN,Hertha BSC,Hamburger SV,01:00:00,domestic_league

In [12]:
df_concat_4 = df_concat_3.merge(df3, on = 'game_id', how = 'outer')
df_concat_4.head()

D:\Anaconda\lib\site-packages\pandas\core\reshape\merge.py:1204: RuntimeWarning: invalid value encountered in cast
  if not (lk == lk.astype(rk.dtype))[~np.isnan(lk)].all():

,player_id_x,name,last_season,current_club_id,player_code,country_of_birth,date_of_birth,sub_position,position_x,foot,...,away_club_name,aggregate,competition_type,game_lineups_id,type,number,player_id_y,player_name_y,team_captain,position_y
0,124732.0,John Anthony Brooks,2023.0,533.0,john-anthony-brooks,Germany,1993-01-28,Centre-Back,Defender,left,...,Hertha BSC,02:03:00,domestic_cup,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,124732.0,John Anthony Brooks,2023.0,533.0,john-anthony-brooks,Germany,1993-01-28,Centre-Back,Defender,left,...,eintracht frankfurt Football ag,06:01:00,domestic_league,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,124732.0,John Anthony Brooks,2023.0,533.0,john-anthony-brooks,Germany,1993-01-28,Centre-Back,Defender,left,...,Hertha BSC,02:02:00,domestic_league,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,49723.0,Timothy Chandler,2023.0,24.0,timothy-chandler,Germany,1990-03-29,Right-Back,Defender,right,...,Hertha BSC,02:02:00,domestic_league,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,124732.0,John Anthony Brooks,2023.0,533.0,john-anthony-brooks,Germany,1993-01-28,Centre-Back,Defender,left,...,Hamburger SV,01:00:00,domestic_league,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df_concat_4.columns

Index(['player_id_x', 'name', 'last_season', 'current_club_id', 'player_code',
       'country_of_birth', 'date_of_birth', 'sub_position', 'position_x',
       'foot', 'height_in_cm', 'market_value_in_eur',
       'highest_market_value_in_eur', 'contract_expiration_date', 'agent_name',
       'appearance_id', 'game_id', 'date_x', 'player_name_x',
       'competition_id_x', 'yellow_cards', 'red_cards', 'goals', 'assists',
       'minutes_played', 'competition_id_y', 'season', 'round', 'date_y',
       'home_club_goals', 'away_club_goals', 'home_club_position',
       'away_club_position', 'home_club_manager_name',
       'away_club_manager_name', 'stadium', 'attendance', 'referee',
       'home_club_formation', 'away_club_formation', 'home_club_name',
       'away_club_name', 'aggregate', 'competition_type', 'game_lineups_id',
       'type', 'number', 'player_id_y', 'player_name_y', 'team_captain',
       'position_y'],
      dtype='object')

In [14]:
df_concat_5 = df_concat_4.merge(df4, on = 'game_id', how = 'outer')
df_concat_5.head()

D:\Anaconda\lib\site-packages\pandas\core\reshape\merge.py:1204: RuntimeWarning: invalid value encountered in cast
  if not (lk == lk.astype(rk.dtype))[~np.isnan(lk)].all():

,player_id_x,name,last_season,current_club_id,player_code,country_of_birth,date_of_birth,sub_position,position_x,foot,...,team_captain,position_y,game_event_id,date,minute,type_y,player_id,description,player_in_id,player_assist_id
0,124732.0,John Anthony Brooks,2023.0,533.0,john-anthony-brooks,Germany,1993-01-28,Centre-Back,Defender,left,...,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN
1,124732.0,John Anthony Brooks,2023.0,533.0,john-anthony-brooks,Germany,1993-01-28,Centre-Back,Defender,left,...,NaN,NaN,8b292ee51350c3b09cbfa946c16742ff,2013-08-10,32.0,Goals,124732.0,", Right-footed shot, 1. Goal of the Season Ass...",NaN,37013.0
2,124732.0,John Anthony Brooks,2023.0,533.0,john-anthony-brooks,Germany,1993-01-28,Centre-Back,Defender,left,...,NaN,NaN,84fb44a2ae9da0808ca882503e08ce6b,2013-08-18,71.0,Cards,49723.0,"1. Yellow card , Foul",NaN,NaN
3,49723.0,Timothy Chandler,2023.0,24.0,timothy-chandler,Germany,1990-03-29,Right-Back,Defender,right,...,NaN,NaN,84fb44a2ae9da0808ca882503e08ce6b,2013-08-18,71.0,Cards,49723.0,"1. Yellow card , Foul",NaN,NaN
4,124732.0,John Anthony Brooks,2023.0,533.0,john-anthony-brooks,Germany,1993-01-28,Centre-Back,Defender,left,...,NaN,NaN,589e6262eb0abbd4792291510d09b2a3,2013-08-24,23.0,Substitutions,124732.0,", Injury",4691.0,NaN

In [15]:
# pd.set_option('display.max_columns', None)
df_concat_5.iloc[19]

player_id_x                                              124732.0
name                                          John Anthony Brooks
last_season                                                2023.0
current_club_id                                             533.0
player_code                                   john-anthony-brooks
country_of_birth                                          Germany
date_of_birth                                 1993-01-28 00:00:00
sub_position                                          Centre-Back
position_x                                               Defender
foot                                                         left
height_in_cm                                                194.0
market_value_in_eur                                     2000000.0
highest_market_value_in_eur                            15000000.0
contract_expiration_date                      2024-06-30 00:00:00
agent_name                                                  ROGON
appearance_id                                      2321346_124732
game_id                                                 2321346.0
date_x                                        2014-05-03 00:00:00
player_name_x                                 John Anthony Brooks
competition_id_x                                               L1
yellow_cards                                                  1.0
red_cards                                                     0.0
goals                                                         0.0
assists                                                       0.0
minutes_played                                               90.0
competition_id_y                                               L1
season                                                     2013.0
round                                                33. Matchday
date_y                                        2014-05-03 00:00:00
home_club_goals                                               2.0
away_club_goals                                               0.0
home_club_position                                           12.0
away_club_position                                           10.0
home_club_manager_name                                 Robin Dutt
away_club_manager_name                                Jos Luhukay
stadium                                   Wohninvest-Weserstadion
attendance                                                42100.0
referee                                           Robert Hartmann
home_club_formation                                           NaN
away_club_formation                                           NaN
home_club_name                 Sportverein Werder Bremen von 1899
away_club_name                                         Hertha BSC
aggregate                                                02:00:00
competition_type                                  domestic_league
game_lineups_id                                               NaN
type_x                                                        NaN
number                                                        NaN
player_id_y                                                   NaN
player_name_y                                                 NaN
team_captain                                                  NaN
position_y                                                    NaN
game_event_id                    a3b7c0ec6a25725c745b8d4ba17818ed
date                                          2014-05-03 00:00:00
minute                                                       56.0
type_y                                                      Cards
player_id                                                124732.0
description                                2. Yellow card  , Foul
player_in_id                                                  NaN
player_assist_id                                              NaN
Name: 19, dtype: object

In [16]:
df_concat_5.isnull().sum()

player_id_x                     877
name                            877
last_season                     877
current_club_id                 877
player_code                     877
country_of_birth                877
date_of_birth                   877
sub_position                    877
position_x                      877
foot                            978
height_in_cm                    936
market_value_in_eur            2182
highest_market_value_in_eur     881
contract_expiration_date       2314
agent_name                     1998
appearance_id                   937
game_id                          60
date_x                          937
player_name_x                   937
competition_id_x                937
yellow_cards                    937
red_cards                       937
goals                           937
assists                         937
minutes_played                  937
competition_id_y                937
season                          937
round                           937
date_y                          937
home_club_goals                 937
away_club_goals                 937
home_club_position             1487
away_club_position             1487
home_club_manager_name          943
away_club_manager_name          943
stadium                         937
attendance                     1078
referee                         942
home_club_formation            4746
away_club_formation            4746
home_club_name                 1065
away_club_name                 1005
aggregate                       937
competition_type                937
game_lineups_id                4502
type_x                         4502
number                         4502
player_id_y                    4502
player_name_y                  4502
team_captain                   4502
position_y                     4502
game_event_id                  2662
date                           2662
minute                         2662
type_y                         2662
player_id                      2662
description                    3677
player_in_id                   3454
player_assist_id               4579
dtype: int64

In [17]:
# We will drop the columns which are showing a high percentage of null values
df_concat_5 = df_concat_5.drop(['home_club_formation','away_club_formation','game_lineups_id','number','player_id_y','player_name_y','team_captain','position_y','player_assist_id','description','player_in_id'],axis = 1)
df_concat_5.head()

,player_id_x,name,last_season,current_club_id,player_code,country_of_birth,date_of_birth,sub_position,position_x,foot,...,home_club_name,away_club_name,aggregate,competition_type,type_x,game_event_id,date,minute,type_y,player_id
0,124732.0,John Anthony Brooks,2023.0,533.0,john-anthony-brooks,Germany,1993-01-28,Centre-Back,Defender,left,...,NaN,Hertha BSC,02:03:00,domestic_cup,NaN,NaN,NaT,NaN,NaN,NaN
1,124732.0,John Anthony Brooks,2023.0,533.0,john-anthony-brooks,Germany,1993-01-28,Centre-Back,Defender,left,...,Hertha BSC,eintracht frankfurt Football ag,06:01:00,domestic_league,NaN,8b292ee51350c3b09cbfa946c16742ff,2013-08-10,32.0,Goals,124732.0
2,124732.0,John Anthony Brooks,2023.0,533.0,john-anthony-brooks,Germany,1993-01-28,Centre-Back,Defender,left,...,1.FC Nuremberg,Hertha BSC,02:02:00,domestic_league,NaN,84fb44a2ae9da0808ca882503e08ce6b,2013-08-18,71.0,Cards,49723.0
3,49723.0,Timothy Chandler,2023.0,24.0,timothy-chandler,Germany,1990-03-29,Right-Back,Defender,right,...,1.FC Nuremberg,Hertha BSC,02:02:00,domestic_league,NaN,84fb44a2ae9da0808ca882503e08ce6b,2013-08-18,71.0,Cards,49723.0
4,124732.0,John Anthony Brooks,2023.0,533.0,john-anthony-brooks,Germany,1993-01-28,Centre-Back,Defender,left,...,Hertha BSC,Hamburger SV,01:00:00,domestic_league,NaN,589e6262eb0abbd4792291510d09b2a3,2013-08-24,23.0,Substitutions,124732.0

In [18]:
df_concat_5.isnull().sum()

player_id_x                     877
name                            877
last_season                     877
current_club_id                 877
player_code                     877
country_of_birth                877
date_of_birth                   877
sub_position                    877
position_x                      877
foot                            978
height_in_cm                    936
market_value_in_eur            2182
highest_market_value_in_eur     881
contract_expiration_date       2314
agent_name                     1998
appearance_id                   937
game_id                          60
date_x                          937
player_name_x                   937
competition_id_x                937
yellow_cards                    937
red_cards                       937
goals                           937
assists                         937
minutes_played                  937
competition_id_y                937
season                          937
round                           937
date_y                          937
home_club_goals                 937
away_club_goals                 937
home_club_position             1487
away_club_position             1487
home_club_manager_name          943
away_club_manager_name          943
stadium                         937
attendance                     1078
referee                         942
home_club_name                 1065
away_club_name                 1005
aggregate                       937
competition_type                937
type_x                         4502
game_event_id                  2662
date                           2662
minute                         2662
type_y                         2662
player_id                      2662
dtype: int64

In [19]:
# removing date_y,competition_id_y column from date_x and date_y, competition_id_x and competition_id_y columns, as both are one and same only
# player_id column will also be dropped as it is a redundant copy of column 'player_id_x' and it has lots of null values also

df_concat_5 = df_concat_5.drop(['date_y','competition_id_y','player_id'],axis = 1)

df_concat_5.head()

,player_id_x,name,last_season,current_club_id,player_code,country_of_birth,date_of_birth,sub_position,position_x,foot,...,referee,home_club_name,away_club_name,aggregate,competition_type,type_x,game_event_id,date,minute,type_y
0,124732.0,John Anthony Brooks,2023.0,533.0,john-anthony-brooks,Germany,1993-01-28,Centre-Back,Defender,left,...,Benjamin Cortus,NaN,Hertha BSC,02:03:00,domestic_cup,NaN,NaN,NaT,NaN,NaN
1,124732.0,John Anthony Brooks,2023.0,533.0,john-anthony-brooks,Germany,1993-01-28,Centre-Back,Defender,left,...,Michael Weiner,Hertha BSC,eintracht frankfurt Football ag,06:01:00,domestic_league,NaN,8b292ee51350c3b09cbfa946c16742ff,2013-08-10,32.0,Goals
2,124732.0,John Anthony Brooks,2023.0,533.0,john-anthony-brooks,Germany,1993-01-28,Centre-Back,Defender,left,...,Guido Winkmann,1.FC Nuremberg,Hertha BSC,02:02:00,domestic_league,NaN,84fb44a2ae9da0808ca882503e08ce6b,2013-08-18,71.0,Cards
3,49723.0,Timothy Chandler,2023.0,24.0,timothy-chandler,Germany,1990-03-29,Right-Back,Defender,right,...,Guido Winkmann,1.FC Nuremberg,Hertha BSC,02:02:00,domestic_league,NaN,84fb44a2ae9da0808ca882503e08ce6b,2013-08-18,71.0,Cards
4,124732.0,John Anthony Brooks,2023.0,533.0,john-anthony-brooks,Germany,1993-01-28,Centre-Back,Defender,left,...,Marco Fritz,Hertha BSC,Hamburger SV,01:00:00,domestic_league,NaN,589e6262eb0abbd4792291510d09b2a3,2013-08-24,23.0,Substitutions

In [20]:
# date column must also be removed as it is a redundant copy of date_x and contains many null values
df_concat_5 = df_concat_5.drop(['date'],axis = 1)
df_concat_5.head()

,player_id_x,name,last_season,current_club_id,player_code,country_of_birth,date_of_birth,sub_position,position_x,foot,...,attendance,referee,home_club_name,away_club_name,aggregate,competition_type,type_x,game_event_id,minute,type_y
0,124732.0,John Anthony Brooks,2023.0,533.0,john-anthony-brooks,Germany,1993-01-28,Centre-Back,Defender,left,...,5446.0,Benjamin Cortus,NaN,Hertha BSC,02:03:00,domestic_cup,NaN,NaN,NaN,NaN
1,124732.0,John Anthony Brooks,2023.0,533.0,john-anthony-brooks,Germany,1993-01-28,Centre-Back,Defender,left,...,54376.0,Michael Weiner,Hertha BSC,eintracht frankfurt Football ag,06:01:00,domestic_league,NaN,8b292ee51350c3b09cbfa946c16742ff,32.0,Goals
2,124732.0,John Anthony Brooks,2023.0,533.0,john-anthony-brooks,Germany,1993-01-28,Centre-Back,Defender,left,...,37068.0,Guido Winkmann,1.FC Nuremberg,Hertha BSC,02:02:00,domestic_league,NaN,84fb44a2ae9da0808ca882503e08ce6b,71.0,Cards
3,49723.0,Timothy Chandler,2023.0,24.0,timothy-chandler,Germany,1990-03-29,Right-Back,Defender,right,...,37068.0,Guido Winkmann,1.FC Nuremberg,Hertha BSC,02:02:00,domestic_league,NaN,84fb44a2ae9da0808ca882503e08ce6b,71.0,Cards
4,124732.0,John Anthony Brooks,2023.0,533.0,john-anthony-brooks,Germany,1993-01-28,Centre-Back,Defender,left,...,63574.0,Marco Fritz,Hertha BSC,Hamburger SV,01:00:00,domestic_league,NaN,589e6262eb0abbd4792291510d09b2a3,23.0,Substitutions

In [21]:
df7 = df_concat_5.select_dtypes(exclude = 'number')
df7.head()

,name,player_code,country_of_birth,date_of_birth,sub_position,position_x,foot,contract_expiration_date,agent_name,appearance_id,...,away_club_manager_name,stadium,referee,home_club_name,away_club_name,aggregate,competition_type,type_x,game_event_id,type_y
0,John Anthony Brooks,john-anthony-brooks,Germany,1993-01-28,Centre-Back,Defender,left,2024-06-30,ROGON,2320457_124732,...,Jos Luhukay,Grummi Arena,Benjamin Cortus,NaN,Hertha BSC,02:03:00,domestic_cup,NaN,NaN,NaN
1,John Anthony Brooks,john-anthony-brooks,Germany,1993-01-28,Centre-Back,Defender,left,2024-06-30,ROGON,2321034_124732,...,Armin Veh,Olympiastadion Berlin,Michael Weiner,Hertha BSC,eintracht frankfurt Football ag,06:01:00,domestic_league,NaN,8b292ee51350c3b09cbfa946c16742ff,Goals
2,John Anthony Brooks,john-anthony-brooks,Germany,1993-01-28,Centre-Back,Defender,left,2024-06-30,ROGON,2321049_124732,...,Jos Luhukay,Max-Morlock-Stadion,Guido Winkmann,1.FC Nuremberg,Hertha BSC,02:02:00,domestic_league,NaN,84fb44a2ae9da0808ca882503e08ce6b,Cards
3,Timothy Chandler,timothy-chandler,Germany,1990-03-29,Right-Back,Defender,right,2025-06-30,NaN,2321049_49723,...,Jos Luhukay,Max-Morlock-Stadion,Guido Winkmann,1.FC Nuremberg,Hertha BSC,02:02:00,domestic_league,NaN,84fb44a2ae9da0808ca882503e08ce6b,Cards
4,John Anthony Brooks,john-anthony-brooks,Germany,1993-01-28,Centre-Back,Defender,left,2024-06-30,ROGON,2321061_124732,...,Thorsten Fink,Olympiastadion Berlin,Marco Fritz,Hertha BSC,Hamburger SV,01:00:00,domestic_league,NaN,589e6262eb0abbd4792291510d09b2a3,Substitutions

In [22]:
df7.isnull().sum()

name                         877
player_code                  877
country_of_birth             877
date_of_birth                877
sub_position                 877
position_x                   877
foot                         978
contract_expiration_date    2314
agent_name                  1998
appearance_id                937
date_x                       937
player_name_x                937
competition_id_x             937
round                        937
home_club_manager_name       943
away_club_manager_name       943
stadium                      937
referee                      942
home_club_name              1065
away_club_name              1005
aggregate                    937
competition_type             937
type_x                      4502
game_event_id               2662
type_y                      2662
dtype: int64

In [23]:
cols = ['contract_expiration_date','agent_name','type_y','type_x']

for i in cols:
    df_concat_5[i].fillna('Unknown',inplace = True)

df_concat_5.isnull().sum()

player_id_x                     877
name                            877
last_season                     877
current_club_id                 877
player_code                     877
country_of_birth                877
date_of_birth                   877
sub_position                    877
position_x                      877
foot                            978
height_in_cm                    936
market_value_in_eur            2182
highest_market_value_in_eur     881
contract_expiration_date          0
agent_name                        0
appearance_id                   937
game_id                          60
date_x                          937
player_name_x                   937
competition_id_x                937
yellow_cards                    937
red_cards                       937
goals                           937
assists                         937
minutes_played                  937
season                          937
round                           937
home_club_goals                 937
away_club_goals                 937
home_club_position             1487
away_club_position             1487
home_club_manager_name          943
away_club_manager_name          943
stadium                         937
attendance                     1078
referee                         942
home_club_name                 1065
away_club_name                 1005
aggregate                       937
competition_type                937
type_x                            0
game_event_id                  2662
minute                         2662
type_y                            0
dtype: int64

In [24]:
for i in df7.columns:
    df_concat_5[i].fillna(df_concat_5[i].mode()[0],inplace = True)

df_concat_5.isnull().sum()

player_id_x                     877
name                              0
last_season                     877
current_club_id                 877
player_code                       0
country_of_birth                  0
date_of_birth                     0
sub_position                      0
position_x                        0
foot                              0
height_in_cm                    936
market_value_in_eur            2182
highest_market_value_in_eur     881
contract_expiration_date          0
agent_name                        0
appearance_id                     0
game_id                          60
date_x                            0
player_name_x                     0
competition_id_x                  0
yellow_cards                    937
red_cards                       937
goals                           937
assists                         937
minutes_played                  937
season                          937
round                             0
home_club_goals                 937
away_club_goals                 937
home_club_position             1487
away_club_position             1487
home_club_manager_name            0
away_club_manager_name            0
stadium                           0
attendance                     1078
referee                           0
home_club_name                    0
away_club_name                    0
aggregate                         0
competition_type                  0
type_x                            0
game_event_id                     0
minute                         2662
type_y                            0
dtype: int64

In [25]:
df_concat_5 = df_concat_5.drop(['game_event_id'],axis = 1)

In [26]:
df_concat_5.isnull().sum()

player_id_x                     877
name                              0
last_season                     877
current_club_id                 877
player_code                       0
country_of_birth                  0
date_of_birth                     0
sub_position                      0
position_x                        0
foot                              0
height_in_cm                    936
market_value_in_eur            2182
highest_market_value_in_eur     881
contract_expiration_date          0
agent_name                        0
appearance_id                     0
game_id                          60
date_x                            0
player_name_x                     0
competition_id_x                  0
yellow_cards                    937
red_cards                       937
goals                           937
assists                         937
minutes_played                  937
season                          937
round                             0
home_club_goals                 937
away_club_goals                 937
home_club_position             1487
away_club_position             1487
home_club_manager_name            0
away_club_manager_name            0
stadium                           0
attendance                     1078
referee                           0
home_club_name                    0
away_club_name                    0
aggregate                         0
competition_type                  0
type_x                            0
minute                         2662
type_y                            0
dtype: int64

In [27]:
num_cols = df_concat_5.select_dtypes(include = 'number')

df_concat_5[num_cols.columns] = df_concat_5[num_cols.columns].apply(lambda x : x.interpolate())

df_concat_5.isnull().sum()

player_id_x                    0
name                           0
last_season                    0
current_club_id                0
player_code                    0
country_of_birth               0
date_of_birth                  0
sub_position                   0
position_x                     0
foot                           0
height_in_cm                   0
market_value_in_eur            0
highest_market_value_in_eur    0
contract_expiration_date       0
agent_name                     0
appearance_id                  0
game_id                        0
date_x                         0
player_name_x                  0
competition_id_x               0
yellow_cards                   0
red_cards                      0
goals                          0
assists                        0
minutes_played                 0
season                         0
round                          0
home_club_goals                0
away_club_goals                0
home_club_position             1
away_club_position             1
home_club_manager_name         0
away_club_manager_name         0
stadium                        0
attendance                     0
referee                        0
home_club_name                 0
away_club_name                 0
aggregate                      0
competition_type               0
type_x                         0
minute                         1
type_y                         0
dtype: int64

In [28]:
df_concat_5.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4746 entries, 0 to 4745
Data columns (total 43 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   player_id_x                  4746 non-null   float64
 1   name                         4746 non-null   object
 2   last_season                  4746 non-null   float64
 3   current_club_id              4746 non-null   float64
 4   player_code                  4746 non-null   object
 5   country_of_birth             4746 non-null   object
 6   date_of_birth                4746 non-null   datetime64[ns]
 7   sub_position                 4746 non-null   object
 8   position_x                   4746 non-null   object
 9   foot                         4746 non-null   object
 10  height_in_cm                 4746 non-null   float64
 11  market_value_in_eur          4746 non-null   float64
 12  highest_market_value_in_eur  4746 non-null   float64
 13  contract_expiration_date     4746 non-null   object
 14  agent_name                   4746 non-null   object
 15  appearance_id                4746 non-null   object
 16  game_id                      4746 non-null   float64
 17  date_x                       4746 non-null   datetime64[ns]
 18  player_name_x                4746 non-null   object
 19  competition_id_x             4746 non-null   object
 20  yellow_cards                 4746 non-null   float64
 21  red_cards                    4746 non-null   float64
 22  goals                        4746 non-null   float64
 23  assists                      4746 non-null   float64
 24  minutes_played               4746 non-null   float64
 25  season                       4746 non-null   float64
 26  round                        4746 non-null   object
 27  home_club_goals              4746 non-null   float64
 28  away_club_goals              4746 non-null   float64
 29  home_club_position           4745 non-null   float64
 30  away_club_position           4745 non-null   float64
 31  home_club_manager_name       4746 non-null   object
 32  away_club_manager_name       4746 non-null   object
 33  stadium                      4746 non-null   object
 34  attendance                   4746 non-null   float64
 35  referee                      4746 non-null   object
 36  home_club_name               4746 non-null   object
 37  away_club_name               4746 non-null   object
 38  aggregate                    4746 non-null   object
 39  competition_type             4746 non-null   object
 40  type_x                       4746 non-null   object
 41  minute                       4745 non-null   float64
 42  type_y                       4746 non-null   object
dtypes: datetime64[ns](2), float64(19), object(22)
memory usage: 1.6+ MB

In [29]:
df_concat_5['minute'].fillna(0.0,inplace = True)

In [30]:
df_concat_5['home_club_position'].fillna(0.0,inplace = True)
df_concat_5['away_club_position'].fillna(0.0,inplace = True)

In [31]:
df_concat_5.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4746 entries, 0 to 4745
Data columns (total 43 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   player_id_x                  4746 non-null   float64
 1   name                         4746 non-null   object
 2   last_season                  4746 non-null   float64
 3   current_club_id              4746 non-null   float64
 4   player_code                  4746 non-null   object
 5   country_of_birth             4746 non-null   object
 6   date_of_birth                4746 non-null   datetime64[ns]
 7   sub_position                 4746 non-null   object
 8   position_x                   4746 non-null   object
 9   foot                         4746 non-null   object
 10  height_in_cm                 4746 non-null   float64
 11  market_value_in_eur          4746 non-null   float64
 12  highest_market_value_in_eur  4746 non-null   float64
 13  contract_expiration_date     4746 non-null   object
 14  agent_name                   4746 non-null   object
 15  appearance_id                4746 non-null   object
 16  game_id                      4746 non-null   float64
 17  date_x                       4746 non-null   datetime64[ns]
 18  player_name_x                4746 non-null   object
 19  competition_id_x             4746 non-null   object
 20  yellow_cards                 4746 non-null   float64
 21  red_cards                    4746 non-null   float64
 22  goals                        4746 non-null   float64
 23  assists                      4746 non-null   float64
 24  minutes_played               4746 non-null   float64
 25  season                       4746 non-null   float64
 26  round                        4746 non-null   object
 27  home_club_goals              4746 non-null   float64
 28  away_club_goals              4746 non-null   float64
 29  home_club_position           4746 non-null   float64
 30  away_club_position           4746 non-null   float64
 31  home_club_manager_name       4746 non-null   object
 32  away_club_manager_name       4746 non-null   object
 33  stadium                      4746 non-null   object
 34  attendance                   4746 non-null   float64
 35  referee                      4746 non-null   object
 36  home_club_name               4746 non-null   object
 37  away_club_name               4746 non-null   object
 38  aggregate                    4746 non-null   object
 39  competition_type             4746 non-null   object
 40  type_x                       4746 non-null   object
 41  minute                       4746 non-null   float64
 42  type_y                       4746 non-null   object
dtypes: datetime64[ns](2), float64(19), object(22)
memory usage: 1.6+ MB

In [32]:
# Filtering the dataset for the condition below, as both the columns mean the same, and then deleting the player_name_x column

In [33]:
df_concat_5 = df_concat_5[df_concat_5['name'] == df_concat_5['player_name_x']]
df_concat_5.shape

(4686, 43)

In [34]:
#df_concat_5 = df_concat_5.drop(['player_name_x'],axis = 1)
df_concat_5.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4686 entries, 0 to 4745
Data columns (total 43 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   player_id_x                  4686 non-null   float64
 1   name                         4686 non-null   object
 2   last_season                  4686 non-null   float64
 3   current_club_id              4686 non-null   float64
 4   player_code                  4686 non-null   object
 5   country_of_birth             4686 non-null   object
 6   date_of_birth                4686 non-null   datetime64[ns]
 7   sub_position                 4686 non-null   object
 8   position_x                   4686 non-null   object
 9   foot                         4686 non-null   object
 10  height_in_cm                 4686 non-null   float64
 11  market_value_in_eur          4686 non-null   float64
 12  highest_market_value_in_eur  4686 non-null   float64
 13  contract_expiration_date     4686 non-null   object
 14  agent_name                   4686 non-null   object
 15  appearance_id                4686 non-null   object
 16  game_id                      4686 non-null   float64
 17  date_x                       4686 non-null   datetime64[ns]
 18  player_name_x                4686 non-null   object
 19  competition_id_x             4686 non-null   object
 20  yellow_cards                 4686 non-null   float64
 21  red_cards                    4686 non-null   float64
 22  goals                        4686 non-null   float64
 23  assists                      4686 non-null   float64
 24  minutes_played               4686 non-null   float64
 25  season                       4686 non-null   float64
 26  round                        4686 non-null   object
 27  home_club_goals              4686 non-null   float64
 28  away_club_goals              4686 non-null   float64
 29  home_club_position           4686 non-null   float64
 30  away_club_position           4686 non-null   float64
 31  home_club_manager_name       4686 non-null   object
 32  away_club_manager_name       4686 non-null   object
 33  stadium                      4686 non-null   object
 34  attendance                   4686 non-null   float64
 35  referee                      4686 non-null   object
 36  home_club_name               4686 non-null   object
 37  away_club_name               4686 non-null   object
 38  aggregate                    4686 non-null   object
 39  competition_type             4686 non-null   object
 40  type_x                       4686 non-null   object
 41  minute                       4686 non-null   float64
 42  type_y                       4686 non-null   object
dtypes: datetime64[ns](2), float64(19), object(22)
memory usage: 1.6+ MB

In [35]:
df_concat_5.columns = df_concat_5.columns.str.replace('_x','')

### **Performance Analysis**
1. How does a player's total minutes played correlate with their goals and assists over different seasons?
2. What is the impact(psychological) of yellow and red cards on a player's overall performance?
3. Optional => Which player consistently performs better in high-pressure matches based on minutes played and card accumulation?

### **Player Profile and Market Value**
1. How does a player's height and dominant foot affect their market value in euros?
2. Are left-footed players more valuable than right-footed players across different leagues?

### **Team Comparison**
1. How do home club and away club positions differ based on match outcomes?
2. Which club shows the biggest seasonal improvement in home and away performances?

### **Attendance and Stadium Analysis**
1. Does attendance spike when certain referees officiate high-stakes matches?
2. Are certain stadiums consistently associated with higher attendance figures?

### **Referee Analysis**
1. Which referees officiate matches with the highest number of yellow and red cards?
2. Are matches officiated by experienced referees less chaotic in terms of cards and fouls?

### **Substitution Patterns**
1. Is there a winning pattern for teams substituting offensive players after the 70th minute?
2. What impact do substitutions have on final match results?

### **Event Analysis**
1. At what minute of the game do most goals occur, and does this vary by competition type?
2. Is there a prime minute when most winning teams score their goals?

### **Competition Analysis**
1. Which competition type has the highest average goals scored per match?
2. Are league-based competitions less aggressive (fewer cards) than cup tournaments?

### **Player Attributes and Demographics**
1. Do taller players have a greater advantage in scoring headers compared to shorter players?
2. What age group of players tends to receive the highest market value?

### **Contract Management**
1. How do contract expiration dates affect a player's performance leading up to renewal?
2. What trends exist in agent representation among high-value players?

In [37]:
df_concat_5.to_csv('Football_data_merged_cleaned.csv',index = False)
print("Done")

Done

# Using SQL to push the dataframe into SQL Database

In [1]:
pip install pymysql sqlalchemy

Requirement already satisfied: pymysql in d:\anaconda\lib\site-packages (1.1.1)
Requirement already satisfied: sqlalchemy in d:\anaconda\lib\site-packages (2.0.37)
Requirement already satisfied: typing-extensions>=4.6.0 in d:\anaconda\lib\site-packages (from sqlalchemy) (4.12.2)
Requirement already satisfied: greenlet!=0.4.17 in d:\anaconda\lib\site-packages (from sqlalchemy) (1.1.1)
Note: you may need to restart the kernel to use updated packages.

In [72]:
from sqlalchemy import create_engine

In [83]:
# Define database connection

engine = create_engine("mysql+pymysql://{user}:{pw}@{host}/{db}"
.format(host='localhost', db='hr', user='root', pw='Gaurav123'))

In [85]:
df_concat_5.to_sql("Football_data_merged_cleaned",engine,index = False)

D:\Anaconda\lib\site-packages\pandas\io\sql.py:1663: UserWarning: The provided table name 'Football_data_merged_cleaned' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  warnings.warn(msg, UserWarning)

4686